### ISSUE TITLE
wasm32 build target 

### ISSUE THREAD

**Issue by devsprint** [GaryBoone/incr_stats#1]
while trying to use the library in a wasm project, I found out that the library could not be compiled to wasm32 target. It looks like `criterion` dependency is the root cause.

An easy fix is to move the `criterion` dependency under dev-dependencies such it is not propagated to other crates that use this crate.

**Comment by devsprint** [comment]
@GaryBoone this issue is fixed now. Can you do a new release? Thank you

**Comment by GaryBoone** [comment]
Done! Updated crate published.
